### ISSUE TITLE
how to add subtitle in video?

### ISSUE THREAD

**Issue by halilozel1903** [kunalbhatia/avp#8]
It has a Subtitle icon, but you did not take any action. Do you have any idea how it's done?

**Comment by pankaj046** [comment]
Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP,
                null, Format.NO_VALUE, Format.NO_VALUE, "en", null, Format.OFFSET_SAMPLE_RELATIVE);
        MediaSource textMediaSource = new SingleSampleMediaSource.Factory(dataSourceFactory)
                .createMediaSource(srtUri, textFormat, C.TIME_UNSET);

MergingMediaSource mediaSource = new MergingMediaSource(videoSource, textMediaSource);

**Comment by pankaj046** [comment]
> It has a Subtitle icon, but you did not take any action. Do you have any idea how it's done?

Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP,
null, Format.NO_VALUE, Format.NO_VALUE, "en", null, Format.OFFSET_SAMPLE_RELATIVE);
MediaSource textMediaSource = new SingleSampleMediaSource.Factory(dataSourceFactory)
.createMediaSource(srtUri, textFormat, C.TIME_UNSET);

MergingMediaSource mediaSource = new MergingMediaSource(videoSource, textMediaSource);

**Comment by kunalbhatia** [comment]
No sir, no idea about it
